controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login_page:
    path: /login
    controller: App\Controller\LoginController::loginPage
