controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login_page:
    path: /login
    controller: App\Controller\LoginController::loginPage
app_google_auth_check:
    path: /connect/google/check
    controller: App\Controller\AuthController::googleAuthCheck

cart:
    path: /cart
    controller: App\Controller\CartController::index

app_edit:
    path: '/edit'
    controller: 'App\Controller\ReservationBack\ResBackController::edit'
    methods: ['GET', 'POST']

send_message:
    path: /send-message
    controller: App\Controller\ChatController::sendPrompt
    methods: [POST]