controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml

cart:
    path: /cart
    controller: App\Controller\CartController::index
