# config/services.yaml

parameters:
    # Put parameters here that don't need to change on each machine where the app is deployed
    # https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    mages_directory: '%kernel.project_dir%/public/uploads'


services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    endroid.qr_code.builder:
        class: Endroid\QrCode\Builder\Builder
    Endroid\QrCode\Builder\BuilderInterface: '@endroid.qr_code.builder'


    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add more service definitions when explicit configuration is needed
    # Please note that last definitions always *replace* previous ones
    App\Entity\Reservation: ~

